### ISSUE TITLE
Sum of transactions does NOT include internal transactions

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/donation-leaderboard#1]
*This is a duplicate from the [old repo Issue#47](https://github.com/geleeroyale/donation-leaderboard/issues/47)*

**Problem:** Fetching the Data through etherscan API get txlist only lists external transactions. Internal transactions seem to be ignored.

Tried to find a solution for this for weeks now. I have visited the Internet all over only to see that seemingly everybody (except etherscan) is having this problem. The question is maybe if the etherscan API also allows other requests, like list internal transactions that we could just add to the board (I should add that we use botth the usual API as well as the websockets API which is even more limited)

**Possible Solutions:**
1 - We find some undocumented(?) etherscan API secret
2 - We make our own scraper (maybe based on @maxskant take on the leaderboard backend or @sponnet's Token Scraper) and listen for the donation event emitted from the multisig for example
3 - We wait until a better API comes along, maybe from an Open Block Explorer

**Comment by status-open-bounty** [comment]
Balance: 0.1 ETH
Tokens: SNT: 500.00
Contract address: [0x0584b4330c858935299aa2074fea54d84425ea18](https://etherscan.io/address/0x0584b4330c858935299aa2074fea54d84425ea18)
Network: Mainnet
Paid to: emazurek
Visit [https://openbounty.status.im](https://openbounty.status.im) to learn more.

**Comment by deamme** [comment]
I think a client-side scraper would be the better solution for now until Open Block Explorer comes along.

**Comment by ewingrj** [comment]
not sure how you're using the api, but etherscan does allow you to fetch internal txs for a given account.

http://api.etherscan.io/api?module=account&action=txlistinternal&address=0x2c1ba59d6f58433fb1eaee7d20b26ed83bda51a3&startblock=0&endblock=2702578&sort=asc&apikey=YourApiKeyToken

**Comment by maxkant** [comment]
@geleeroyale are you still looking for a solution? I've just been making a feathers app that stores contract events, so if that's a potential path to the solution, I could probably put something together pretty quickly.

**Comment by deamme** [comment]
If Etherscan has an API for it then it's even easier because we are already using the API from them.

**Comment by DaveAppleton** [comment]
Parity have a function call to list internal tx

**Comment by geleeroyale** [comment]
@maxkant @deamme @DaveAppleton @emazurek - **Ed IS great** and included internal txs in a pull request that is currently under review (PR#7) by using a new call in the etherscan API

We want to move away from using the etherscan API asap. But we want to conserve the easy deployability of the leaderboard for different campaigns, so the larger scope is to use an open API.

If we can make and run a scraper that can act as an API for many leaderboards I am down to try

**Comment by sponnet** [comment]
Totally doable IMO, when do you want to set it up?

**Comment by geleeroyale** [comment]
Yeah @sponnet - We missed you so much in Toronto! The time to implement is always now :-D ... However, maybe we can coordinate this endeavour. I don't know what is best for coordinating contributions on big features - should we have a call about this? @sponnet @maxkant @emazurek @deamme ?

**Comment by geleeroyale** [comment]
@emazurek Thank you for supplying a fix - I implemented it on most leaderboards by now. Please link an eth account to your github via openbounty.status.im and make a stub pull request referencing this issue(like making a small change in readme and making a pull request referencing this issue here) - so we can pay out the bounty!

**Comment by geleeroyale** [comment]
I also just noticed that this fix adds all internal transactions - also outgoing ones :fire: 

Edit: Is there a way to single out *incoming* internal transactions? etherscan API does not offer any insight
Edit2: Filter-out transactions from the ```donationAdress```?
Edit3: Nevermind - solution from Edit #2 worked

**Comment by sponnet** [comment]
What was the solution in the end then like @geleeroyale  ?? Just curious to know. Thx.

**Comment by geleeroyale** [comment]
@sponnet Etherscan added ```list internal transactions``` to their API, so we are just able to fetch that as well and filter out outgoing transactions by checking the ```from``` value against the donation address when sorting out the list.

It works great as long as etherscan works well. I think this is still only a temporary fix until a better API comes along.

**Comment by wildmolasses** [comment]
Maybe if I reference my pull request here #9 then the bounty will have better odds of going through! Thanks again.

**Comment by deamme** [comment]
I guess this issue can be closed?

**Comment by geleeroyale** [comment]
yes @deamme - we will - just having some difficulties with the bounty payout. once the payout worked, we will close it
